ALTER TABLE comments
ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS source_type VARCHAR(50) NOT NULL DEFAULT 'NORMAL',
ADD CONSTRAINT chk_source_type CHECK (source_type IN ('NORMAL', 'SOCIAL_SHARE'));
